backend:
  name: github
  repo: hensparty/hensparty.github.io
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "itinerary"
    label: "Itinerary"
    files:
      - name: "program"
        label: "Program data"
        file: "content/program-data.js"
        format: "raw"
        fields:
          - { name: "body", label: "Program data file", widget: "text" }
